### PR TITLE
Build Gaussian Blur for color images and closes #512

### LINKED ISSUE #512: Gaussian blur for color images
Tutorial about implementing `vpImageFilter::gaussianBlur()` on RGB color images must be introduced.Extending it may be by introducing simultaneous grabbing image using color camera.

### PR DESCRIPTION
**Pull request by yshkp**
Gaussian Blur now available for RGB images with all formats specified earlier.

### CODE REVIEW

**Comment by fspindle** [comment]
@yshkp Thanks.

I don't know if the prototype of your `void vpImageFilter::filterX()` and `void vpImageFilter::filterY()` functions are the best since the output is a `vpRGBa` that has `unsigned char` values, meaning that you will loose precision compared to `double` values.
Introducing double should leed to the following prototypes:
```
static void filterX(const vpImage<vpRGBa> &I, vpImage<double> &dIRx, vpImage<double> &dIGx, vpImage<double> &dIBx, const double *filter, unsigned int size);
static void filterY(const vpImage<vpRGBa> &I, vpImage<double> &dIRx, vpImage<double> &dIGx, vpImage<double> &dIBx, const double *filter, unsigned int size);
static void filterX(const vpImage<double> &IR, const vpImage<double> &IG, const vpImage<double> &IB, vpImage<double> &dIRx, vpImage<double> &dIGx, vpImage<double> &dIBx, const double *filter, unsigned int size);
static void filterY(const vpImage<double> &IR, const vpImage<double> &IG, const vpImage<double> &IB, vpImage<double> &dIRx, vpImage<double> &dIGx, vpImage<double> &dIBx, const double *filter, unsigned int size);
```

and
```
static void gaussianBlur(const vpImage<vpRGBa> &I, vpImage<double> &GIR, vpImage<double> &GIG, vpImage<double> &GIB, unsigned int size = 7, double sigma = 0., bool normalize = true);
```
Right now, my opinion is that the prototypes I mention previously are heavy and not generic enough to consider other color coding like HSV. I would say that the best would be to split the color channels and filter each of them leading to a single new function with something like:
```
static void gaussianBlur(const vpImage<vpRGBa> &I, vpImage<double> &I_blurred_R, vpImage<double> &I_blurred_G, vpImage<double> &I_blurred_B, unsigned int size = 7, double sigma = 0., bool normalize = true)
{
    vpImage<unsigned char> I_R, I_G, I_B;

    vpImageConvert::split(I, &I_R, &I_G, &I_B);
    vpImageFilter::gaussianBlur(I_R, I_blurred_R, size, sigma, normalize);
    vpImageFilter::gaussianBlur(I_G, I_blurred_G, size, sigma, normalize);
    vpImageFilter::gaussianBlur(I_B, I_blurred_B, size, sigma, normalize);
}
```

@s-trinh What do you think about ?

@yshkp Anyway, could you please introduce a test for the new `vpImageFilter::gaussianBlur(vpImage<vpRGBa>)` function that you wrote. This test will also help us to see what is the precision lost.

The test should be introduced in `modules/core/test/image/testImageFilter.cpp`.
It should read `Klimt.ppm` image compare results obtained with `vpImageFilter::gaussianBlur(vpImage<vpRGBa>)` with those obtained using a separate filtering of the R, G, B components. The pseudo-code could be something similat to:
```
    vpImage<RGBa> I_rgb; // Klimt.ppm
    // Test on real image
    if (opt_ppath.empty()) {
      filename = vpIoTools::createFilePath(ipath, "Klimt/Klimt.ppm");
      vpImageIo::read(I_rgb, filename);
    } else {
      filename = opt_ppath;
      vpImageIo::read(I_rgb, filename);
      printf("Image \"%s\" read successfully\n", filename.c_str());
    }

    vpImage<unsigned char> I_R, I_G, I_B;
    vpImage<double> I_blurred_R, I_blurred_G, I_blurred_B;
    vpImage<RGBa> I_rgb_blurred;

    vpImageFilter::gaussianBlur(I_rgb, I_rgb_blurred);

    vpImageConvert::split(I_rgb, &I_R, &I_G, &I_B);
    vpImageFilter::gaussianBlur(I_R, I_blurred_R);
    vpImageFilter::gaussianBlur(I_G, I_blurred_G);
    vpImageFilter::gaussianBlur(I_B, I_blurred_B, size);

    for (unsigned int i=0; i< I.getHeight(); i++) {
      for (unsigned int j=0; j< I.getWidth(); j++) {
         // test if I_rgb_blurred[i][j].R =  I_blurred_R[i][j];
         // test if I_rgb_blurred[i][j].G =  I_blurred_G[i][j];
         // test if I_rgb_blurred[i][j].B =  I_blurred_B[i][j];
     }
    }
```
In the component comparison there should be may be a `static_cast<unsigned char>` or a `vpMath::round()` call to cast/compare `double` to `unsigned char` values. To compare 2 values, use `vpMath::equal()` that has a tolerance threshold

**Comment by yshkp** [comment]
@fspindle Yup, I tried my prototype in `tutorial-image-filter.cpp` and outputs are attached here.I used `moneky.ppm` as an input. 

screenshot from 2019-02-07 17-23-17
screenshot from 2019-02-07 17-23-27
screenshot from 2019-02-07 17-23-36

Soon I will be adding test also in `testImageFilter.cpp`. Just to make a start I used this prototype and modifications will improve its precision. To make it successful run I used tutorial and If you want I can also add it as test. You please have a look in results and then we will work on its improvement.

**Comment by s-trinh** [comment]
@fspindle 

In my opinion, there should be two interfaces:

- `static void gaussianBlur(const vpImage<unsigned char> &I, vpImage<double> &GI, unsigned int size = 7, double sigma = 0., bool normalize = true);` for more mathematical oriented applications
- `static void gaussianBlur(const vpImage<unsigned char> &I, vpImage<unsigned char> &GI, unsigned int size = 7, double sigma = 0., bool normalize = true);` for image processing applications (when you just want to reduce the image noise before applying other vision algorithm in the image)
 - and similarly for `vpRGBa` image, `static void gaussianBlur(const vpImage<vpRGBa> &I, vpImage<double> &GI_R, vpImage<double> &GI_G, vpImage<double> &GI_B, unsigned int size = 7, double sigma = 0., bool normalize = true);` (better variable names to be found?)
- `static void gaussianBlur(const vpImage<vpRGBa> &I, vpImage<vpRGBa> &GI, unsigned int size = 7, double sigma = 0., bool normalize = true);` 

For `vpRGBa` type, splitting approach is the easiest way to go and avoids the need to introduce functions with `vpRGBa` support.

**Comment by fspindle** [comment]
@yshkp Sorry but `./tutorial-image-filter monkey.ppm` doesn't call your function since the image has `vpImage<insigned char> I` prototype. As suggested in my previous post, modify `modules/core/test/image/testImageFilter.cpp` in order to test the function.

@s-trinh I agree

**Comment by yshkp** [comment]
@fspindle Yeah I know it has the prototype of `vpImage<unsigned char> I`. I just changed to `vpImage<vpRGBa> I` for testing my prototype.

**Comment by yshkp** [comment]
So going as per your suggestion new prototype shall be build which cover the mathematical problem for grayscale as well as RGB images.
@fspindle Then the prototype `static void gaussianBlur(const vpImage<vpRGBa> &I, vpImage<vpRGBa> &GI, unsigned int size = 7, double sigma = 0., bool normalize = true);` could be merged and soon I will be adding test in `modules/core/test/image/testImageFilter.cpp`  for this prototype as well as working on the other interface mentioned by @s-trinh for image processing.

**Comment by yshkp** [comment]
@fspindle As of now, Do I just need to add a test on gaussian blur based on prototype written by me and simply display the image ?

**Comment by fspindle** [comment]
@yshkp Yes

**Pull request merged**
