### PR TITLE
Tracking with mask

### PR DESCRIPTION
**Pull request by MSimonInria**
Mask for edge only
Bug to fix: some me appear outside the mask

### CODE REVIEW

**Comment by fspindle** [comment]
I just discover that my review was not sent. It is maybe obsolete now.

**Comment by fspindle** [comment]
@s-trinh Sounds ok to me. Could you have a look ? Thanks

**Comment by s-trinh** [comment]
I am reviewing, I would like to add some tests also.

**Comment by s-trinh** [comment]
I have made some modifications.
Feel free to check that everything is ok.

**Comment by MSimonInria** [comment]
Ok for me.
Thank you for writing tests.

**Pull request merged**
