### PR TITLE
Wrapping imgproc module

### PR DESCRIPTION
**Pull request by AKS1996**
Just added vpContour. Need to app vpImgproc

### CODE REVIEW

**Comment by AKS1996** [comment]
@fspindle [Try this](https://github.com/AKS1996/GSOC-Prep/tree/simple_graphics/visp-java-demos/visp-imgproc-module-demo) `imgproc` module demo in Eclipse. I'm wrapping `vpContours.h`, will add it soon.

**Comment by AKS1996** [comment]
@fspindle I'm unable to run [this](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-contour_8cpp-example.html) `vpContour` tutorial. 

I've tried it on a different system too. `findContours` function is producing SIGSEV. Did you try running it recently?

**Comment by fspindle** [comment]
I works on my mac with OpenCV 3.4.0.

**Comment by AKS1996** [comment]
@fspindle It works on mac but I don't know why `vpContour` demo isn't working on ubuntu. 
Anyway the build will works well and `VpImgproc` demo runs fine.

Let's merge it for now. I'll try to see what's the bug (I'll try it on fedora too).

**Comment by fspindle** [comment]
I tried to run the vpContour [tutorial](http://visp-doc.inria.fr/doxygen/visp-daily/tutorial-contour_8cpp-example.html) on Ubuntu 16.04 with OpenCV 2.4.9.1 and it works!

**Pull request merged**
