### PR TITLE
Build Android SDK

### PR DESCRIPTION
**Pull request by AKS1996**

### CODE REVIEW

**Comment by AKS1996** [comment]
@fspindle Its strange again on travis :smile: 
> The job exceeded the maximum time limit for jobs, and has been terminated

**Comment by s-trinh** [comment]
I have restarted the job.

**Comment by s-trinh** [comment]
I am trying to build ViSP Android SDK with:
`ccmake -DCMAKE_TOOLCHAIN_FILE=<path to ViSP>/platforms/android/android.toolchain.cmake -DANDROID_NDK=<path to android ndk>/android-ndk-r17b -DANDROID_NATIVE_API_LEVEL=android-18 -DANDROID_ABI="armeabi-v7a with NEON" ../<path to ViSP>`

But I have this CMake error:

```
CMake Warning at platforms/android/android.toolchain.cmake:335 (message):
   Could not determine machine name for compiler from
   <path to android ndk>/android-ndk-r17b/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64
 Call Stack (most recent call first):
   platforms/android/android.toolchain.cmake:562 (__DETECT_TOOLCHAIN_MACHINE_NAME)
   platforms/android/android.toolchain.cmake:619 (__GLOB_NDK_TOOLCHAINS)
   <path to ViSP build>/CMakeFiles/3.5.1/CMakeSystem.cmake:6 (include)
   CMakeLists.txt:84 (project)



 CMake Warning at platforms/android/android.toolchain.cmake:335 (message):
   Could not determine machine name for compiler from
   <path to android ndk>/android-ndk-r17b/toolchains/mipsel-linux-android-4.9/prebuilt/linux-x86_64
 Call Stack (most recent call first):
   platforms/android/android.toolchain.cmake:562 (__DETECT_TOOLCHAIN_MACHINE_NAME)
   platforms/android/android.toolchain.cmake:619 (__GLOB_NDK_TOOLCHAINS)
   <path to ViSP build>/ViSP_android_ndk/CMakeFiles/3.5.1/CMakeSystem.cmake:6 (include)
   CMakeLists.txt:84 (project)



 CMake Error at cmake/android/android_gradle_projects.cmake:1 (message):
```

Any idea what I am doing wrong?

**Comment by s-trinh** [comment]
Thanks for the info.
Just for the record, on Ubuntu 16.04 I had to:
- download a newer version of CMake, beware with ROS you cannot uninstall CMake from the distribution without removing some parts of ROS, [see](https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu#comment1492832_829311)
```
CMake Error at /home/strinh/Android/android-ndk-r17b/build/cmake/android.toolchain.cmake:40 (cmake_minimum_required):
  CMake 3.6.0 or higher is required.  You are running version 3.5.1
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt:84 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "build_sdk.py", line 357, in <module>
    builder.build_library(abi, do_install)
  File "build_sdk.py", line 174, in build_library
    execute(cmd)
  File "build_sdk.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1
```

- downgrade the Android SDK version:
```
CMake Error at cmake/android/android_gradle_projects.cmake:1 (message):
  

  Android gradle-based build/projects are not supported in this version of
  ViSP.

  You need to downgrade Android SDK Tools to version 25.2.5.

Call Stack (most recent call first):
  cmake/android/ViSPDetectAndroidSDK.cmake:204 (include)
  CMakeLists.txt:734 (include)
```

Now I have these, so I guess it is more or less ok for now?
```
[325/500] Building ViSP Android library project
FAILED: cd /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk && /usr/bin/ant -q -noinput -k debug -Djava.target=1.7 -Djava.source=1.7 && /home/strinh/cmake-3.12.0-Linux-x86_64/bin/cmake -E touch /home/strinh/ViSP/ViSP_android_ndk/o4a/CMakeFiles/dephelper/visp_java_android
   [subant] No sub-builds to iterate on
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:25: error: cannot find symbol
    [javac] import org.visp.core.CvType;
    [javac]                     ^
    [javac]   symbol:   class CvType
    [javac]   location: package org.visp.core
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:26: error: cannot find symbol
    [javac] import org.visp.core.Mat;
    [javac]                     ^
    [javac]   symbol:   class Mat
    [javac]   location: package org.visp.core
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:27: error: cannot find symbol
    [javac] import org.visp.imgproc.Imgproc;
    [javac]                        ^
    [javac]   symbol:   class Imgproc
    [javac]   location: package org.visp.imgproc
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:327: error: cannot find symbol
    [javac]         public Mat gray() {
    [javac]                ^
    [javac]   symbol:   class Mat
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:332: error: cannot find symbol
    [javac]         public Mat rgba() {
    [javac]                ^
    [javac]   symbol:   class Mat
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:346: error: cannot find symbol
    [javac]         public JavaCamera2Frame(Mat Yuv420sp, int width, int height) {
    [javac]                                 ^
    [javac]   symbol:   class Mat
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:355: error: cannot find symbol
    [javac]         public JavaCamera2Frame(Mat Y, Mat UV, int width, int height) {
    [javac]                                 ^
    [javac]   symbol:   class Mat
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:355: error: cannot find symbol
    [javac]         public JavaCamera2Frame(Mat Y, Mat UV, int width, int height) {
    [javac]                                        ^
    [javac]   symbol:   class Mat
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:368: error: cannot find symbol
    [javac]         private Mat mYuvFrameData;
    [javac]                 ^
    [javac]   symbol:   class Mat
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:369: error: cannot find symbol
    [javac]         private Mat mUVFrameData;
    [javac]                 ^
    [javac]   symbol:   class Mat
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:370: error: cannot find symbol
    [javac]         private Mat mRgba;
    [javac]                 ^
    [javac]   symbol:   class Mat
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:183: error: cannot find symbol
    [javac]                     Mat y_mat = new Mat(h, w, CvType.CV_8UC1, y_plane);
    [javac]                     ^
    [javac]   symbol: class Mat
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:183: error: cannot find symbol
    [javac]                     Mat y_mat = new Mat(h, w, CvType.CV_8UC1, y_plane);
    [javac]                                     ^
    [javac]   symbol: class Mat
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:183: error: cannot find symbol
    [javac]                     Mat y_mat = new Mat(h, w, CvType.CV_8UC1, y_plane);
    [javac]                                               ^
    [javac]   symbol: variable CvType
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:184: error: cannot find symbol
    [javac]                     Mat uv_mat = new Mat(h / 2, w / 2, CvType.CV_8UC2, uv_plane);
    [javac]                     ^
    [javac]   symbol: class Mat
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:184: error: cannot find symbol
    [javac]                     Mat uv_mat = new Mat(h / 2, w / 2, CvType.CV_8UC2, uv_plane);
    [javac]                                      ^
    [javac]   symbol: class Mat
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:184: error: cannot find symbol
    [javac]                     Mat uv_mat = new Mat(h / 2, w / 2, CvType.CV_8UC2, uv_plane);
    [javac]                                                        ^
    [javac]   symbol: variable CvType
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:334: error: cannot find symbol
    [javac]                 Imgproc.cvtColor(mYuvFrameData, mRgba, Imgproc.COLOR_YUV2RGBA_NV21, 4);
    [javac]                                                        ^
    [javac]   symbol:   variable Imgproc
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:334: error: cannot find symbol
    [javac]                 Imgproc.cvtColor(mYuvFrameData, mRgba, Imgproc.COLOR_YUV2RGBA_NV21, 4);
    [javac]                 ^
    [javac]   symbol:   variable Imgproc
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:336: error: cannot find symbol
    [javac]                 Imgproc.cvtColor(mYuvFrameData, mRgba, Imgproc.COLOR_YUV2RGB_I420, 4); // COLOR_YUV2RGBA_YV12 produces inverted colors
    [javac]                                                        ^
    [javac]   symbol:   variable Imgproc
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:336: error: cannot find symbol
    [javac]                 Imgproc.cvtColor(mYuvFrameData, mRgba, Imgproc.COLOR_YUV2RGB_I420, 4); // COLOR_YUV2RGBA_YV12 produces inverted colors
    [javac]                 ^
    [javac]   symbol:   variable Imgproc
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:339: error: cannot find symbol
    [javac]                 Imgproc.cvtColorTwoPlane(mYuvFrameData, mUVFrameData, mRgba, Imgproc.COLOR_YUV2RGBA_NV21);
    [javac]                                                                              ^
    [javac]   symbol:   variable Imgproc
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:339: error: cannot find symbol
    [javac]                 Imgproc.cvtColorTwoPlane(mYuvFrameData, mUVFrameData, mRgba, Imgproc.COLOR_YUV2RGBA_NV21);
    [javac]                 ^
    [javac]   symbol:   variable Imgproc
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:352: error: cannot find symbol
    [javac]             mRgba = new Mat();
    [javac]                         ^
    [javac]   symbol:   class Mat
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] /home/strinh/ViSP/ViSP_android_ndk/o4a/android_sdk/src/org/visp/android/JavaCamera2View.java:361: error: cannot find symbol
    [javac]             mRgba = new Mat();
    [javac]                         ^
    [javac]   symbol:   class Mat
    [javac]   location: class JavaCamera2View.JavaCamera2Frame
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 25 errors
Target '-compile' failed with message 'The following error occurred while executing this line:
/home/strinh/Android/Sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.'.
Cannot execute '-dex' - '-compile' failed or was not executed.
Cannot execute '-package' - '-dex' failed or was not executed.
Cannot execute '-do-debug' - '-package' failed or was not executed.
Cannot execute 'debug' - '-do-debug' failed or was not executed.
```

**Comment by AKS1996** [comment]
Yes @s-trinh , that downgrading the Android SDK is an issue(latest revisions don't support much functionality).

The `Mat` and `CvType` errors were due to old files(I forgot to change a lot of stuff from OpenCV's android platform earlier :sweat_smile: ). But I've edited the files. Checkout the `android_platform` branch and then try the build. You won't get those errors.

**Comment by s-trinh** [comment]
I have these:
```
[337/500] Building CXX object modules/java/jni/CMakeFiles/visp_java.dir/__/generator/src/cpp/visp_java.cpp.o
FAILED: /home/strinh/Android/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ --sysroot=/home/strinh/Android/android-ndk-r17b/sysroot  -Dvisp_EXPORTS -Iinclude -I/home/strinh/ViSP/ViSP-github/modules/java/generator/src/cpp -Imodules/java_bindings_generator/gen/cpp -I/home/strinh/ViSP/ViSP-github/modules/core/include -I/home/strinh/ViSP/ViSP-github/modules/imgproc/include -isystem /home/strinh/Android/android-ndk-r17b/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /home/strinh/Android/android-ndk-r17b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem /home/strinh/Android/android-ndk-r17b/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystem /home/strinh/Android/android-ndk-r17b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security    -Wall -Wextra -fopenmp -fvisibility=hidden -fPIC -Os -DNDEBUG  -fPIC -MD -MT modules/java/jni/CMakeFiles/visp_java.dir/__/generator/src/cpp/visp_java.cpp.o -MF modules/java/jni/CMakeFiles/visp_java.dir/__/generator/src/cpp/visp_java.cpp.o.d -o modules/java/jni/CMakeFiles/visp_java.dir/__/generator/src/cpp/visp_java.cpp.o -c /home/strinh/ViSP/ViSP-github/modules/java/generator/src/cpp/visp_java.cpp
In file included from modules/java_bindings_generator/gen/cpp/visp_jni.hpp:1:0,
                 from /home/strinh/ViSP/ViSP-github/modules/java/generator/src/cpp/visp_java.cpp:4:
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp: In function 'jint Java_org_visp_core_VpMatrix_pseudoInverseOpenCV_10(JNIEnv*, jclass, jlong, jlong, jdouble)':
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp:3601:24: error: 'class vpMatrix' has no member named 'pseudoInverseOpenCV'
     int _retval_ = me->pseudoInverseOpenCV( Ap, (double)svThreshold );
                        ^
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp: In function 'jint Java_org_visp_core_VpMatrix_pseudoInverseOpenCV_11(JNIEnv*, jclass, jlong, jlong)':
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp:3622:24: error: 'class vpMatrix' has no member named 'pseudoInverseOpenCV'
     int _retval_ = me->pseudoInverseOpenCV( Ap );
                        ^
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp: In function 'jint Java_org_visp_core_VpMatrix_pseudoInverseOpenCV_12(JNIEnv*, jclass, jlong, jlong, jlong, jdouble, jlong, jlong, jlong)':
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp:3651:24: error: 'class vpMatrix' has no member named 'pseudoInverseOpenCV'
     int _retval_ = me->pseudoInverseOpenCV( Ap, sv, (double)svThreshold, imA, imAt, kerAt );
                        ^
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp: In function 'jint Java_org_visp_core_VpMatrix_pseudoInverseOpenCV_13(JNIEnv*, jclass, jlong, jlong, jlong, jdouble)':
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp:3677:24: error: 'class vpMatrix' has no member named 'pseudoInverseOpenCV'
     int _retval_ = me->pseudoInverseOpenCV( Ap, sv, (double)svThreshold );
                        ^
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp: In function 'jint Java_org_visp_core_VpMatrix_pseudoInverseOpenCV_14(JNIEnv*, jclass, jlong, jlong, jlong)':
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp:3699:24: error: 'class vpMatrix' has no member named 'pseudoInverseOpenCV'
     int _retval_ = me->pseudoInverseOpenCV( Ap, sv );
                        ^
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp: In function 'jlong Java_org_visp_core_VpMatrix_inverseByLUOpenCV_10(JNIEnv*, jclass, jlong)':
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp:5471:29: error: 'class vpMatrix' has no member named 'inverseByLUOpenCV'
     vpMatrix _retval_ = me->inverseByLUOpenCV(  );
                             ^
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp: In function 'jlong Java_org_visp_core_VpMatrix_pseudoInverseOpenCV_15(JNIEnv*, jclass, jlong, jdouble)':
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp:5725:29: error: 'class vpMatrix' has no member named 'pseudoInverseOpenCV'
     vpMatrix _retval_ = me->pseudoInverseOpenCV( (double)svThreshold );
                             ^
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp: In function 'jlong Java_org_visp_core_VpMatrix_pseudoInverseOpenCV_16(JNIEnv*, jclass, jlong)':
/home/strinh/ViSP/ViSP_android_ndk/o4a/modules/java_bindings_generator/gen/cpp/core.inl.hpp:5745:29: error: 'class vpMatrix' has no member named 'pseudoInverseOpenCV'
     vpMatrix _retval_ = me->pseudoInverseOpenCV(  );
                             ^
[337/500] Building CXX object 3rdparty/apriltag/CMakeFiles/visp_apriltag.dir/tag36h10.c.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "build_sdk.py", line 363, in <module>
    builder.build_library(abi, do_install)
  File "build_sdk.py", line 177, in build_library
    execute(["ninja"])
  File "build_sdk.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1

```

**Comment by AKS1996** [comment]
@s-trinh Android wasn't discovering OpenCV libraries, thats why the errors. PR  #413 will add `#if defined(...)` sort of code to avoid compilation errors

**Comment by AKS1996** [comment]
Depends on #413

**Comment by s-trinh** [comment]
I took the liberty to rebase on master to have PR #413 and fix some warnings and build errors.

**Comment by s-trinh** [comment]
I have this error:
```
-- Build files have been written to: /home/strinh/ViSP/ViSP_android_ndk/build_service_armeabi-v7a
Traceback (most recent call last):
  File "build_sdk.py", line 370, in <module>
    builder.build_engine(abi, engdest)
  File "build_sdk.py", line 201, in build_engine
    assert os.path.exists(apkdest), apkdest
AssertionError: /home/strinh/ViSP/ViSP_android_ndk/build_service_armeabi-v7a/platforms/android/service/engine/.build
```
My command line is:
`python3 build_sdk.py --no_ccache --config ndk-16.config.py --sdk_path /home/strinh/Android/Sdk --ndk_path /home/strinh/Android/android-ndk-r17b --build /home/strinh/ViSP/ViSP_android_ndk`

Did I miss something?

**Comment by AKS1996** [comment]
I'm working on it. I compared this build with opencv one's, and it seems that the cmake directory for platforms/android/engine is missing.

Will update u by tomorrow

**Comment by AKS1996** [comment]
@s-trinh Try building it now
I've skipped sample apps for now. I'll be testing whether the engine.apk file works or not and then create some samples

I've tested with given config file and previous command as yours
```python
ABIs = [
#    ABI("2", "armeabi-v7a", "arm-linux-androideabi-4.9", cmake_vars=dict(ANDROID_ABI='armeabi-v7a with NEON')),
#    ABI("1", "armeabi",     "arm-linux-androideabi-4.9", cmake_vars=dict(WITH_TBB='OFF')),
#    ABI("3", "arm64-v8a",   "aarch64-linux-android-4.9"),
    ABI("5", "x86_64",      "x86_64-4.9"),
#    ABI("4", "x86",         "x86-4.9")
]
```

**Comment by s-trinh** [comment]
:+1: 
Yes, the build is working fine now.

**Comment by AKS1996** [comment]
The SDK works fine on my Android Oreo x86_64 emulator(finally :smile: ). Here are the steps(same as that of opencv, taken [from here](https://stackoverflow.com/a/27421494/8243704) )

+ Create a new android project with API > 21
+ Hit on File -> New -> Import Module and Import `visp-sdk-build/sdk/java` folder (I'm looking into why it has that weird name `viSPLoader320`)
+ add  `implementation project(':viSPLibrary320')` in `app/build.gradle` file
+ Create a folder named `jniLibs` under `app/src/main`
+ Create a folder named `x86_64` in `jniLibs` and copy all libraries from `visp-sdk-build/lib` here
+ Get the source code for MainActivity.java [here](https://github.com/AKS1996/GSOC-Prep/blob/master/visp-android-demos/HelloVisp/app/src/main/java/example/vispdemo/MainActivity.java) (usage is same as that of Java Linux)

Also, u can try importing the project [from here](https://github.com/AKS1996/GSOC-Prep/tree/master/visp-android-demos/HelloVisp).

**Comment by AKS1996** [comment]
I've tested `core` and `imgproc` modules. Now, I'll try to
+ Test other modules to show a apriltag detection demo
+ Turn the above steps into a VISP SDK tutorial
+ Create sample apks as in as OpenCV SDK
+ Checkout build for other versions

It's 8th today. I wanted to complete above tasks at least a day before the submission deadline( i.e. 14th)

**Comment by AKS1996** [comment]
@fspindle @s-trinh The build is working for `x86`, `x86_64`, `armeabi-v7a` and `arm64-v8a`. I've dropped `mips` architecture coz its not supported by latest Android NDK versions

**Pull request merged**
