### PR TITLE
Minor improvements for image moments

### PR DESCRIPTION
**Pull request by francofusco**
Following the discussion in #661, here there is a small PR that slightly improves `vpFeatureMomentArea` by making sure that the interaction matrix in the discrete case is that of `mu20+mu02` (as in `vpMomentArea`).

Regarding the evaluation of the interaction matrix of Alpha, I saw that the source code already had a [`vpFeatureMomentAlpha::compute_interaction()`](https://github.com/lagadic/visp/blob/0266a1e6c6a25a83bfda4188ab021435b4043e7a/modules/visual_features/src/visual-feature/vpFeatureMomentAlpha.cpp#L49) method that uses the version I was proposing. It is protected by a `#ifdef VISP_MOMENTS_COMBINE_MATRICES` guard. For the moment, I just edited that version. Before going on, I wanted to know what you prefer to do:
- Keep only one definition (the one that is currently ignored)
- Still give the user the possibility to decide which one to use via the `VISP_MOMENTS_COMBINE_MATRICES`, and fixing the second version (as discussed, using `beta=2` and `gamma=1` should solve the problem)

I would probably go for the second one, since I see that many other moments have this feature.

### CODE REVIEW

**Comment by fspindle** [comment]
I would suggest to give the user the possibility to decide which version to use with `ENABLE_MOMENTS_COMBINE_MATRICES` cmake option changing `beta=2` and `gamma=1` in `vpFeatureMomentAlpha.cpp` when discrete.

Moreover, instead to make `ENABLE_MOMENTS_COMBINE_MATRICES` advanced, I suggest also to modify in the main `CMakeLists.txt` file the line:

```
VP_OPTION(ENABLE_MOMENTS_COMBINE_MATRICES  "" "" "Use linear combination of matrices instead of linear combination of moments to compute interaction matrices." "" OFF)
```
so that the user can choose easily during configuration which version to use

**Comment by francofusco** [comment]
I updated `vpFeatureMomentAlpha::compute_interaction()` so that `beta=2`. I removed `gamma` since it is equal to 1 in both cases. I also updated the option in the `CMakeLists.txt` to make it non-advanced as you suggested.

Before making and pushing the commit, however, I wanted to understand one thing. Depending on `VISP_MOMENTS_COMBINE_MATRICES`, two definitions of the class `vpFeatureMomentAlpha` can be generated (see [here](https://github.com/lagadic/visp/blob/0266a1e6c6a25a83bfda4188ab021435b4043e7a/modules/visual_features/include/visp3/visual_features/vpFeatureMomentAlpha.h#L52) and [here](https://github.com/lagadic/visp/blob/0266a1e6c6a25a83bfda4188ab021435b4043e7a/modules/visual_features/include/visp3/visual_features/vpFeatureMomentAlpha.h#L111)). The main difference, aside from the different implementation of `compute_interaction()` is that the method [`error()`](https://github.com/lagadic/visp/blob/0266a1e6c6a25a83bfda4188ab021435b4043e7a/modules/visual_features/include/visp3/visual_features/vpFeatureMomentAlpha.h#L194) is defined only when using the "expanded interaction", *i.e.*, when `ENABLE_MOMENTS_COMBINE_MATRICES` is `OFF`. Is there a specific reason for this? I believe that such distinction is not necessary, and that the `error` method should be the same for both. If this is the case, I would change `vpFeatureMomentAlpha.h` so that it uses a single class definition, to avoid the risk of creating different interfaces. I would also keep the `#ifdef VISP_MOMENTS_COMBINE_MATRICES ... #else ... #end` guard only in `vpFeatureMomentAlpha.cpp` - wrapping just `compute_interaction()` - for a cleaner code. Does it sound good?

**Comment by fspindle** [comment]
I agree, there should be a single class definition. I let you proceed to the changes

**Comment by francofusco** [comment]
I applied the last changes! If CI succeeds, then it should be ready for a merge :+1:

**Comment by fspindle** [comment]
Thanks

**Pull request merged**
