### PR TITLE
Add lon-lat sampling and quaternion interpolation methods

### PR DESCRIPTION
**Pull request by s-trinh**
TODO:
- ~~[ ] validate lon-lat visually~~ (to be done maybe later, currently only Catch2 test is implemented)
- ~~[ ] validate quaternion interpolation visually~~ (to be done maybe later, currently only Catch2 test is implemented)

---

Add some code for functions I had to use before with Matplotlib or in personal C++ code, to be used as "reference/example code" and for back-up purposes.

### Lon-Lat sampling

To be able to generate some camera poses in Blender for instance.

image
*Lon-Lat spherical sampling*

image
*Lon-Lat and equidistributed sphere sampling*

### Quaternion interpolation

Slerp to try to do some kind of camera trajectories. It does the job for simple interpolation tasks, but probably B-splines are more appropriate.

Example of this in the following video:

[H2020 PULSAR](https://youtu.be/SaoC67rYp0g?t=86 "H2020 PULSAR")

### CODE REVIEW

**Comment by fspindle** [comment]
@s-trinh There remain warnings:

```
[ 46%] Building CXX object modules/core/CMakeFiles/visp_core.dir/src/math/matrix/vpColVector.cpp.o
/Users/fspindle/soft/visp/visp_ws/test-pr/visp-s-trinh/visp/modules/core/src/math/matrix/vpColVector.cpp:897:12: warning: returning reference to local temporary object [-Wreturn-stack-address]
    return *this / sqrt(sum_square);
           ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/fspindle/soft/visp/visp_ws/test-pr/visp-s-trinh/visp/modules/core/src/math/matrix/vpColVector.cpp:1236:80: warning: returning reference to local temporary object [-Wreturn-stack-address]
const vpColVector &vpColVector::crossProd(const vpColVector &b) const { return vpColVector::crossProd(*this, b); }
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
```

**Comment by s-trinh** [comment]
@fspindle 

Thanks, I will ping you back when the PR is fixed and finished.

**Comment by s-trinh** [comment]
@fspindle 

PR is finished.

---

image

image

**Comment by fspindle** [comment]
@s-trinh Thanks. Can you please add a quick doc in [script/README.md](https://github.com/lagadic/visp/blob/master/script/README.md) with a section dedicated to `LonLatCamPosesVisualizer.py` and `Blender/look_at.py` explaining how to to use them on a quick use case

**Comment by s-trinh** [comment]
I have added two figures and quick text explaining the purpose of the scripts.

**Comment by fspindle** [comment]
@s-trinh Thanks

**Pull request merged**
