### PR TITLE
frames indices calculation without open() call

### PR DESCRIPTION
**Pull request by yurriy**
Improvement from issue #154

### CODE REVIEW

**Comment by fspindle** [comment]
Works well for an image sequence, but not with a video file (ie .mp4 handled with OpenCV). I used the following code for testing:

````
#include <iostream>
#include <visp3/visp.h>

int main(int argc, const char *argv[])
{
  try {
    if (argc == 1) {
      std::cout << "Usage: " << argv[0] << " <image sequence>" << std::endl;
      return 0;
    }
    vpImage<unsigned char> I;
    vpVideoReader grabber;
    grabber.setFileName(argv[1]);
    if (argc > 2) {
      std::cout << "Call open()" << std::endl;
      grabber.open(I);
    }
    std::cout << "First: " << grabber.getFirstFrameIndex() << " last: " << grabber.getLastFrameIndex() << std::endl;
  }
  catch(const vpException &e) {
    std::cout << "Catched exception: " << e.getStringMessage() << std::endl;
  }
}
````

and here the result:

````
$ ./get-first-last-frame ../video/video-1-24.mp4 
First: 0 last: 0
````

**Comment by yurriy** [comment]
It must return -1 for video files?

**Comment by fspindle** [comment]
Not -1 but 1L for first frame and the value of the last frame.

What I suggest:
- create a new private function `void getProperties()` that contains more or less what is in `open()` and that updates the fisrt, last frame number, the image size and set isOpen to true
- Then `open()` becomes 
````
void vpVideoReader::open(vpImage<unsigned char> &I) {
  getProperties();
  I.resize(height, width);
}
````
- modify `getFirstFrame()` with something similar to:
````
getFirstFrame() {
  if (!isOpen) {
    getProperties();
  }
  return firstFrame;
}
````
and similarly for `getLastFrame()` with something similar to:
````
getLastFrame() {
  if (!isOpen) {
    getProperties();
  }
  return lastFrame;
}
````

**Comment by fspindle** [comment]
Based on my previous comment I have introduced a more generic way to get video properties (first and last frame, framerate) in PR #215

**Pull request closed without merging**
