### PR TITLE
Update macos-11 and macos-12 to macos-latest for Github runners

### PR DESCRIPTION
**Pull request by s-trinh**
See:
- https://github.com/actions/runner-images/issues/9255
- https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/

https://github.com/actions/runner-images/issues/9255

[300882082-ac6ef1f1-8e18-4af1-a97f-d38cf82885df](https://github.com/actions/runner-images/issues/9255)

### CODE REVIEW

**Comment by rolalaro** [comment]
The pull request #1419 is blocked due to the fact that no MacOS 11 runner takes the job, is there a chance it is related to this PR ? (I'm not familiar with Github runners, please excuse mu if the question is dumb)

**Comment by s-trinh** [comment]
@rolalaro 
Yes, I believe so.

**Comment by rolalaro** [comment]
> @rolalaro Yes, I believe so.

OK thanks =)

**Comment by fspindle** [comment]
@s-trinh Thanks

**Pull request merged**
