### PR TITLE
Add install docs

### PR DESCRIPTION
**Pull request by AKS1996**
Will add images soon

### CODE REVIEW

**Comment by AKS1996** [comment]
@fspindle @s-trinh 

Try [this example](https://github.com/AKS1996/GSOC-Prep/tree/master/visp-android-demos/AprilTagDetection). It's same as as the native apriltag detection example, except that it doesn't uses NDK, but the ViSP SDK. [This line](https://github.com/AKS1996/GSOC-Prep/blob/master/visp-android-demos/AprilTagDetection/app/src/main/java/example/apriltagdetection/CameraPreview.java#L156) is particularly interesting.

Anyway, this example includes glue code to access android camera framework. In next example, I'll use the ViSP Camera Framework(same task, less code). Then I'll try to show some GUI features using Android OpenGL.

**Comment by AKS1996** [comment]
Forgot to mention. You need to copy libraries(generated via android build) into `app/src/main/jniLibs` folder.

**Comment by s-trinh** [comment]
Thanks, the AprilTag Android demo works well :+1:
Here a screenshot from my phone:
apriltag_android_test

---

In the future, probably we will need to add a custom Java binding to allow accessing the values of `VpHomogeneousMatrix` (`VpHomogeneousMatrix.convert(double[] M)` did not work for me), something similar to `VpImageUChar.getPixel(int i, int j)`. Same thing for `VpMatrix`, `VpColVector`, ...
Displays of AprilTag frames are ad hoc and is not completely ok.
Processing time is around 260 / 300 ms for 3 detected tags and 1920x1080 resolution. Oddly, it is bigger (around 1 s) when there is no detected tag.

**Comment by fspindle** [comment]
@AKS1996 Thanks a lot for your great work. I'm wondering if you plan to complete tutorial-android-getting-started.doc even if the GSoC program is finished or not ?

**Comment by fspindle** [comment]
Thanks a lot.

**Comment by AKS1996** [comment]
Also, I maintained a list of improvements/bugs throughout the summer project(what @s-trinh mentioned [here](https://github.com/lagadic/visp/pull/417#issuecomment-414187784) is an example).

Unfortunately, I couldn't complete all of them(and my acads will take up most of my time now :smile:  ). But, they will improve the SDK for sure.

### java module
#### add pure tests
+ create pure tests in Java
+ import java testing in travis

#### VpImage
+ add jni exception support and delete/finalize to vplmage
+ add library PNG and JPEG flags everywhere in generated JNI code if not installed
+ add more fucntions to vplmage

#### windows
+ Need to test installation in Windows 32 bit(I faced a lot of bugs). 
+ Create a complete package for Windows. [Ninite](https://ninite.com/) seemed to me a really cool tool. Install Python, MinGW x86_32, CMake, Git, Java, all at once. 

### android platform 
+ get libraries list in StaticHelper.java
+ add tests for NDK build
+ implement android samples in `samples` directory

#### Detection using SDK
The SDK is still missing `bitmapToVpImage` and `vpImageToBitmap` methods(as OpenCV [has here](https://github.com/opencv/opencv/blob/master/modules/java/generator/src/cpp/utils.cpp) in `module/java/src/cpp` folders). Adding them will surely remove a lot of glue code for beginners(although I believe that Android developers will find the doc I wrote useful, since it'll offer them great flexibility over the Android Camera API's).

**Comment by ViokingTung** [comment]
> Also, I maintained a list of improvements/bugs throughout the summer project(what @s-trinh mentioned [here](https://github.com/lagadic/visp/pull/417#issuecomment-414187784) is an example).
> 
> Unfortunately, I couldn't complete all of them(and my acads will take up most of my time now 😄 ). But, they will improve the SDK for sure.
> 
> ### java module
> #### add pure tests
> * create pure tests in Java
> * import java testing in travis
> 
> #### VpImage
> * add jni exception support and delete/finalize to vplmage
> * add library PNG and JPEG flags everywhere in generated JNI code if not installed
> * add more fucntions to vplmage
> 
> #### windows
> * Need to test installation in Windows 32 bit(I faced a lot of bugs).
> * Create a complete package for Windows. [Ninite](https://ninite.com/) seemed to me a really cool tool. Install Python, MinGW x86_32, CMake, Git, Java, all at once.
> 
> ### android platform
> * get libraries list in StaticHelper.java
> * add tests for NDK build
> * implement android samples in `samples` directory
> 
> #### Detection using SDK
> The SDK is still missing `bitmapToVpImage` and `vpImageToBitmap` methods(as OpenCV [has here](https://github.com/opencv/opencv/blob/master/modules/java/generator/src/cpp/utils.cpp) in `module/java/src/cpp` folders). Adding them will surely remove a lot of glue code for beginners(although I believe that Android developers will find the doc I wrote useful, since it'll offer them great flexibility over the Android Camera API's).

hi,according to your comment, I tried to convert bitmap to VpImageUChar,I referred to this [code](https://github.com/lagadic/visp/blob/master/modules/core/src/image/vpImageConvert.cpp#L447-L466),rewrite by android but failed, could you give me some advice,thanks. below is my code.
```java
		//load android image
		Bitmap bitmap = BitmapFactory.decodeFile(file_path);
        Mat mat = new Mat();	//argb
        Bitmap bmp32 = bitmap.copy(Bitmap.Config.ARGB_8888, true);
        Utils.bitmapToMat(bmp32, mat);
        Mat grayMat = new Mat();	//gray
        Imgproc.cvtColor(mat, grayMat, Imgproc.COLOR_RGBA2GRAY);
        Mat resizedMat = new Mat();	//resize
        Imgproc.resize(grayMat, resizedMat, new Size(w, h));
        byte[] imgData = new byte[(int) (resizedMat.total() * resizedMat.channels())];
		VpImageUChar imageUChar = new VpImageUChar(imgData, w, h, true);
        VpDetectorAprilTag detectorAprilTag = new VpDetectorAprilTag();
        List<VpHomogeneousMatrix> matrices = detectorAprilTag.detect(imageUChar,tagSize,cameraParameters);
```

**Pull request merged**
