### PR TITLE
First and last image determination

### PR DESCRIPTION
**Pull request by yurriy**
vpVideoReader :: findFirstFrameIndex(), ::findLastFrameIndex() functions now read directory files, where images must be located, and extract the lowest/highest index of image with specified format.

### CODE REVIEW

**Comment by fspindle** [comment]
Nice. Thanks. Works well under OSX. I will check tomorrow under WIndows/Ubuntu.

My comment concerns sscanf() usage:
- Could you please remove sscanf() usage that brings warning with static analysis tools like cppcheck or Coverity Scan. 
- It should be possible to do the same in c++.

PS: Following this work, I think that vpVideoReader could be improved more (see #154 and #155).

**Comment by fspindle** [comment]
Sorry but image format like `I%d.pgm` or `I%10d.pgm` (with digit greater than 9) are not supported. 

    vpException: Format of image name wasn't recognized: I%10d.pgm

**Comment by yurriy** [comment]
@fspindle, thanks, fixed.
Note that the behavior is a little bit more restricted, than it was with sscanf: now it checks that image's index has the length exactly which was specified between % and d, or that it doesn't contain leading zeros, if specifier "%d" was used.

**Comment by fspindle** [comment]
Sounds ok for me.

Able to consider %d and %0xd names

@Souriya Any remark ?

**Comment by s-trinh** [comment]
Looks also ok for me.

@yurriy Maybe you could add a note to clarify the behavior of `getDirFiles()`?

- looks like it returns the list of files and subdirectories (tested on Ubuntu, it includes also `..` and `.`?)

- with no predefined order (tested on Ubuntu)

**Comment by fspindle** [comment]
Thanks Souriya you are right.

@yurriy  I propose that you remove `..` and `.` from the list returned by `getDirFiles()`

**Comment by fspindle** [comment]
Doesn't build under windows with msvc 2017.
There is `cctype` include that defines `std::isdigit()` that is missing.
Just add `#include <cctype>` in `vpVideoReader.cpp`

**Comment by fspindle** [comment]
Works under Windows but you should also remove `.` and `..`
Once done I will merge.

**Comment by yurriy** [comment]
@fspindle 
Does it still return . and ..? I thought I removed it in bf6c5b52de39bd6cde063ba6e67482e1fed44cc9

**Comment by fspindle** [comment]
Yes under windows it returns also `.`and `..`
What you have introduced in bf6c5b5 is only for unix. The same should be done for windows.

**Comment by fspindle** [comment]
Thanks

**Pull request merged**
