### PR TITLE
Adding Tutorial : AprilTag Real Time Detection on iOS

### PR DESCRIPTION
**Pull request by shirahamax**
Dear @fspindle ,

I released AprilTag iOS App with your great library last year.
I want to contribute your library and community.
Would you still be interested in live camera tutorial?

I've already made the tutorial but I'm concerned about the structure of the tutorial, English correctness, and the copyright notice/license of the following files.
- VispDetector.mm
- VideoCapture.swift

I'd appreciate it if you could reply at your convenience.

Thank you :)

### CODE REVIEW

**Comment by fspindle** [comment]
Thanks a lot for your nice contribution that I want to merge.

But before, as mentioned [here](http://visp.inria.fr/contributing-code/) could you please fill the copyright transfer [form](https://visp-doc.inria.fr/right-transfert/visp-right-transfer.pdf) and send it to me at `Fabien.Spindler @ inria.fr` (without spaces). I will then introduce minor changes (typo, ref...)

Concerning `VispDetector.mm` and `VideoCapture.swift` including the copyright as you did is the right way.

Thanks again

**Comment by shirahamax** [comment]
Hi @fspindle,
Thank you for your kind guidance.

I have a question:
there is a file that is merged from MIT files, which is named `VideoCapture.swift`.
Original source codes of this are created by 3rd party, so it seems a little bit difficult to get rights transfer approval.

Then I find a sentence on your [form](https://visp-doc.inria.fr/right-transfert/visp-right-transfer.pdf): 
> Contributions that are intended to be entirely contained inside the designed third party contribution subtree of the ViSP source code distribution are not subject to this rights tranfer contract.

**How do you think of making `3rdparty` folder on my App and putting `VideoCapture.swift` in it?**
like this:
スクリーンショット 2019-06-05 13 08 24

Does it work?
OR, you think I'd better get contact with 3rd party author?

Thank you for your help.

**Comment by fspindle** [comment]
I think that it's a good idea to move `VideoCapture.swift` in `AprilTagLiveCamera/3rdparty` folder as you did.

Concerning MIT licence, _there's absolutely no restriction on commercial use in there. The only requirement is that you must include the MIT copyright notice with any copies of the software. It's a free license, and allows you to use the software for any purpose you might like, including commercial and for-profit use_.

That's why, I don't think that you need to contact the author. Moving the file in the `3rdparty` folder is enough.

**Comment by fspindle** [comment]
@shirahamax I'm waiting for the copyright transfer [form](http://visp-doc.inria.fr/right-transfert/visp-right-transfer.pdf) before I can merge your nice contrib

**Comment by shirahamax** [comment]
@fspindle I'm sorry for late reply. I'm currently receiving internal legal checks, so the form submission is likely to be next week. :pray::pray:

**Comment by fspindle** [comment]
@shirahamax Any updates concerning the copyright transfert form ?

**Comment by shirahamax** [comment]
@fspindle I'm sorry for late action. I send it now. please check 👍 
Is there anything else I can do?

**Pull request merged**
