### PR TITLE
Introduce eclipse tutorial

### PR DESCRIPTION
**Pull request by Lrakulka**
I did the tutorial but I have troubles with the image path. Doxygen don't include images to the html folder that is why I did it manually. This issue causes the same problem in other tutorials.
Also I found strange links in tutorial-getting-started.doc \ref tuto_install_sdk and \ref tuto_install_src which works on your site(http://visp-doc.inria.fr) but locally they don't.

Of course, I may have this problems because I am very new to doxygen.
Anyway have a look at my tutorial and give me your feedback.

Best regards,
Oleksandr

### CODE REVIEW

**Comment by fspindle** [comment]
Thanks for your contribution. It is in the spirit of what was expected.

Could you please improve the PR by:

- renaming all the images in ``doc/image/tutorial-import-visp-into-eclipseide-*`` into ``doc/image/img-visp-into-eclipse-*`` to match the polycing already used consisting in prefixing all the images from the tutorials by ``img-``
- some of the images are too heavy. Could you try to compress a little bit more those that are larger than 80 kb to reach this value if they remain readable
- In ``doc/tutorial.doc`` I would rather introduce your tuto in ``Getting Started`` section rather than in ``Other Tools``. Doing so will give more visibility to the tuto
- modify ``doc/mainpage.doc.in`` to introduce also the tutorial in the main page, under ``Getting Started`` section
- modify the title: ``Tutorial: How to import a CMake project that uses ViSP in Eclipse IDE``
- in ``tutorial-import-visp-into-EclipseIDE.doc``
  - typo: ``Cmake`` -> ``CMake``
  - Line 7: you will learn how to import a CMake project "that uses ViSP" into... 
  - Line 20: ...which ~~uses~~ "is used"
  - Line 32: Goto to the Project directory and execute "cmake . " in console in order to \ref tutorial-getting-started.html#image_unix_config
  - Line 35 & 46 & 60 & 73: Right click on ~~the ViSP~~ Project
  - Line 37 & 38 & 43 & 75: Remove the tabulation before "Make sure..." and replace the tabulation by a "-" to have a list instead of a code presentation of the recommandations
  - introduce a next section that could point to \ref tutorial-image-display (as it is done in ``doc/tutorial-getting-started.doc``)
- modify ``doc/tutorial-getting-started.doc`` in order to add a ref to your new tutorial in the "Next tutorial" section

**Comment by fspindle** [comment]
Thanks

**Comment by Lrakulka** [comment]
Wait a second

**Comment by fspindle** [comment]
If you want to do other modifications you can create a new PR

**Comment by Lrakulka** [comment]
Okey.
I just finished another improvement for this branch

**Pull request merged**
