### PR TITLE
Update Apriltag test and perf

### LINKED ISSUE #538: Apriltag id not available in Android / Java wrapper
The c++-way of reading the tag-id is parsing the message from the detector. There is however no function in the Java wrapper which returns this message. If I am wrong, could somebody tell me how to get the apriltag ids corresponding to the HomogeneousMatrices?

### PR DESCRIPTION
**Pull request by s-trinh**
needs lagadic/visp-images#11

closes #538 

Remove `const` for native datatype in function parameters, [see](https://abseil.io/tips/109).
Since Apriltag detection should be one of the most used functionality, add a proper test procedure to avoid issue like this: #667

### CODE REVIEW

**Comment by s-trinh** [comment]
Add Java sample code to test Java binding for Apriltag detection:

image

image

---

Some notes.

`VpDisplay` class has been commented with this [commit](https://github.com/lagadic/visp/commit/c8d3288be3d520d9e70a6d5f3a9cadf67f70e7e2). Probably a better way would be to ignore this file when building for Android?

Also, in `VpDisplay` there are some mismatch between `i,j` coordinates with `x,y` coordinates. See this Java sample for working code.

**Comment by s-trinh** [comment]
@fspindle 
Can you have a look on this?
Main changes are:
  - add copy ctor and assignment operator for `vpDetectorAprilTag`
  - add `getTagsId()` to avoid having to parse the message for getting the tag id
  - add `getTagsCorners()` to return corners for all the previously detected tags
  - add `setAprilTagFamily()` to change the tag family at any moment
  - improve the tests to cover more use cases
  - add Java sample for Apriltag detection

**Comment by fspindle** [comment]
@s-trinh This new java sample is very useful. I will introduce a new doxygen tutorial to explain how to run it.

On my side everything is ok appart this issue that occurs when opening PGM image like `visp-images/AprilTag/AprilTag.pgm`

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at ApriltagDetection$1.actionPerformed(ApriltagDetection.java:85)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
```
It sounds that PNM format is not supported natively by `ImageIO.read()`. Do you install a plugin as suggested [here](https://stackoverflow.com/questions/22869957/java-imageio-read-image-in-ppm-format-return-null) ?

This is confirmed adding
```
String[] names = ImageIO.getReaderFormatNames();
for (String n : names) {
  System.out.println("Supported format is " + n);
}
```

That shows:
```
Supported format is JPG
Supported format is jpg
Supported format is tiff
Supported format is bmp
Supported format is BMP
Supported format is gif
Supported format is GIF
Supported format is WBMP
Supported format is png
Supported format is PNG
Supported format is JPEG
Supported format is tif
Supported format is TIF
Supported format is TIFF
Supported format is wbmp
Supported format is jpeg
```

A possible fix is to remove `pgm` and `ppm` from
```
fc.setFileFilter(new FileNameExtensionFilter("Image Files (*.jpg, *.jpeg, *.png, *.pgm, *.ppm)",
                                                                   "jpg", "jpeg", "png", "pgm", "ppm"));
```

**Comment by s-trinh** [comment]
Yes it will not read PGM/PNM image format.
It is a small mistake. You can use instead something like in the other Java experimentation code:

https://github.com/lagadic/visp/blob/5b1733c4a4983d43ca6722c3b6c1e01381de64ab/tutorial/tracking/model-based/generic-Java/GenericTracker.java#L160-L161

**Comment by fspindle** [comment]
Thanks a lot.

**Pull request merged**
