### PR TITLE
Add pugixml third-party

### PR DESCRIPTION
**Pull request by s-trinh**
Add pugixml as a third-party library to be able to parse and save XML files "natively".

### CODE REVIEW

**Comment by fspindle** [comment]
@s-trinh Perfect, thanks. Sounds ok to me. Tested on OSX and Windows. I think that we could merge this PR

**Comment by s-trinh** [comment]
There are still 2 classes that need to be updated:

- `vpXmlParserHomogeneousMatrix`
- `vpXmlParserRectOriented`

**Comment by s-trinh** [comment]
The PR should be complete now.

Probably the documentation and the site should be updated to remove the dependency to `libxml2` for the MBT module (there is still `vpXmlParser` with `libxml2` required but this class is not used in ViSP anymore):

- http://visp.inria.fr/software-architecture/
- https://visp.inria.fr/3rdparty_mbt/
- https://visp.inria.fr/3rd_xml2/

**Comment by s-trinh** [comment]
Data are now saved in full precision.
There should be no more precision loss when saving then reading an XML file and compat.

**Comment by fspindle** [comment]
@s-trinh I propose to remove `vpXmlParser` class, `testXmlParser.cpp` and all the cmake material to detect `libxml2` (`FindICONV.cmake`, `FindXML2.cmake`). Do you agree ?

**Comment by fspindle** [comment]
@s-trinh Finally, I don't think that it's a good idea to remove `vpXmlParser` class since it could potentially break compat with previous releases.

**Pull request merged**
