### PR TITLE
Demo code: in-memory image encoding and npz data encoding

### PR DESCRIPTION
**Pull request by s-trinh**
### Why
- on another project, I have discovered the [`.npy`](https://numpy.org/doc/stable/reference/generated/numpy.save.html) or [`.npz`](https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html) file formats used in NumPy
- for a ROS project I have used [`cnpy`](https://github.com/rogersce/cnpy) for my needs: for a sequence of data, save some basic datatypes (int, bool, ...) and save some vector of double data
- it should allow exchanging data easily between C++ and Python/NumPy
- maybe this file format can also be useful here

### But
- the ViSP library is already quite big and only if it is beneficial to other people this code can be added
- it requires C++11 and lots of works are still needed to clean the code
- I have used `cnpy` but I have not searched if better options exist or if there are already in ViSP the code to achieve the same thing

### What
- the demo code is:
  - in `tutorial-mb-generic-tracker-save.cpp`, save the images + some data to be displayed into a `npz` file
  - in `tutorial-mb-generic-tracker-read.cpp`, open the `npz` file, display the images + the model of the teabox

### How
- code from the [cnpy](https://github.com/rogersce/cnpy) library are directly included into the `vpIoTools` class for facility
- `readPNGfromMem` and `writePNGtoMem` functions are added to be able to save compressed image data using code from the stb library, the same can be done for `jpg` encoding
- warning: Java binding must be disable to be able to build the library correctly

### CODE REVIEW

**Comment by fspindle** [comment]
@s-trinh Nice job. Can I merge or do you want to add other functionalities?

**Comment by s-trinh** [comment]
@fspindle Thanks!

To be done:
- read/write with OpenCV backend for color images
- handling of alpha channel with OpenCV backend
- check if RGBa to RGB conversion is needed with stb lib wrt. to this `stride_bytes` param
- show how to check if a data variable is present in a npz file with C++ code?
- add some basic unit tests?
- add some demo code with Python?

I will ping you back when the PR will be ready.

**Comment by s-trinh** [comment]
@fspindle PR is ready from my side.

To quickly test:
- `./tutorial-mb-generic-tracker-save`
- `./tutorial-mb-generic-tracker-read`
- `./tutorial-mb-generic-tracker-full --video [...]/visp-images/mbt/cube/image%04d.png --model [...]/visp-images/mbt/cube_and_cylinder.cao --save test/tracking_%06d.png --save-results test/tracking_results.npz`
- `python3 PlotCameraTrajectory.py -p [...]/test/tracking_results.npz --npz -m [...]/visp-images/mbt/cube_and_cylinder.cao`

Note:
- data are not compressed when using `visp::cnpy::npz_save()` (it is not equivalent to [numpy.savez_compressed](https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html))
- you can open a `npz` file on Linux with an archive manager software

---

PR https://github.com/lagadic/visp/pull/1311 reintroduced some C++98 compatibility code.
Does it mean ViSP is no more a >= C++11 library (https://github.com/lagadic/visp/pull/1267)?

Should we add the minimum C++ version required for the ViSP library here? https://github.com/lagadic/visp/blob/master/README.md

---

TODO one day:
- looks like there is some bug when plotting cylinder object with `PlotCameraTrajectory.py` script (I think the error is how to draw a cylinder and coordinates)

**Comment by fspindle** [comment]
@s-trinh Thanks.

As far as c++98 is concerned, we need to reintroduce this functionality for a project we have with a partner. The idea is to make an effort to make it possible to build ViSP with c++98, but certainly not to port all the classes to c++98. In ViSP you can continue to develop and use c++11 and later features, just remember to disable them if c++98.

**Comment by s-trinh** [comment]
Is there any public news on this project?

**Pull request merged**
