### PR TITLE
Add support for PCL 1.11.0

### LINKED ISSUE #763: VISP does not support the latest PCL release 1.11.0
Hey. I'm just opening the issue in case you intend to support the latest version of PCL. Currently 1.11.0 is failing in configuration. I bumped into the problem while trying to update PCL's formula in homebrew.

Platform: macOS Catalina 
CMake: 3.17.2

Dump:
```
CMake Error at modules/sensor/CMakeLists.txt:209 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_IMPLIB_NONE" is not allowed.


CMake Error at modules/sensor/CMakeLists.txt:211 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_LOCATION_NONE" is not allowed.


CMake Error at modules/sensor/CMakeLists.txt:209 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_IMPLIB_RELEASE" is not allowed.


CMake Error at modules/sensor/CMakeLists.txt:211 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_LOCATION_RELEASE" is not allowed.


CMake Error at modules/sensor/CMakeLists.txt:209 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_IMPLIB_DEBUG" is not allowed.


CMake Error at modules/sensor/CMakeLists.txt:211 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_LOCATION_DEBUG" is not allowed.


CMake Error at modules/sensor/CMakeLists.txt:209 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_IMPLIB_RELEASEWITHDEBINFO" is not allowed.


CMake Error at modules/sensor/CMakeLists.txt:211 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_LOCATION_RELEASEWITHDEBINFO" is not allowed.


CMake Error at modules/sensor/CMakeLists.txt:209 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_IMPLIB_RELWITHDEBINFO" is not allowed.


CMake Error at modules/sensor/CMakeLists.txt:211 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "IMPORTED_LOCATION_RELWITHDEBINFO" is not allowed.

```

### PR DESCRIPTION
**Pull request by SergioRAgostinho**
Closes #763 

Extends support to the latest version of PCL, which was originally broken due to a couple of libraries in PCL now being properly reported as interface (header-only).

I hereby also waive any of my rights to this code and you're even free to commit this code under your own authorship just to avoid having to go through all the trouble of having to scan/sign/send back your contributor contract.

### CODE REVIEW

**Comment by fspindle** [comment]
@SergioRAgostinho Thanks for this PR. Not tested yet, but sounds ok to me. In order to merge, can you please fill the [copyright transfer form](http://visp-doc.inria.fr/right-transfert/visp-right-transfer.pdf) and send it back to Fabien.Spindler at inria.fr

**Comment by fspindle** [comment]
@SergioRAgostinho Any update. Is it ok for the copyright transfer form ?

**Comment by SergioRAgostinho** [comment]
Hey @fspindle apologies for the delay. I'm not interested in going through Inria's process of code contribution and copyright transfer to formalize my contribution.

My intention was simply to exemplify how to address the problem and make it very clear that it is open to the world to use, more specifically the visp maintenance team ;)

Like I originally mentioned, feel free to commit it under your own authorship.

**Comment by fspindle** [comment]
@SergioRAgostinho You are welcome. I just wanted to be sure. Thanks again. I didn't want to appropriate your work without a new confirmation.

**Pull request closed without merging**
