### PR TITLE
Munkres Assignment Algorithm

### PR DESCRIPTION
**Pull request by JuInria**
Munkres Assignment Algorithm (**C++ >= 17**):
  - Class: vpMunkres (`visp/modules/core/include/visp3/core/munkres/vpMunkres.h`)
  - Tests (classic + catch2): `visp/modules/core/test/munkres/testMunkres.cpp`
  - Tutorial: `visp/tutorial/munkres`
  - Doxygen: vpMunkres class + tutorial

### CODE REVIEW

**Comment by fspindle** [comment]
@JuInria Thanks. I did some minor changes.
I suggest to remove the `munkres` namespace to avoid redondant naming `munkres::vpMunkres::`.  
Since in this namespace we will not add any other class, for me it could be removed. Your opinion ?

**Comment by JuInria** [comment]
> @JuInria Thanks. I did some minor changes. I suggest to remove the `munkres` namespace to avoid redondant naming `munkres::vpMunkres::`. Since in this namespace we will not add any other class, for me it could be removed. Your opinion ?

Namespace can be useful to "protect" forward declaration in headers. But as ViSP is not using any namespace, "munkres" namespace does not make any sense. It can be deleted.

**Comment by fspindle** [comment]
@JuInria It remains 2 doxygen warnings. Can you try to fix them

```
/Users/visp/visp_ws/visp/modules/core/src/munkres/vpMunkres.cpp:477: warning: no matching class member found for 
  template vpMunkres::STEP_T vpMunkres::stepTwo< input_data_type >(std::vector< std::vector< double > > &, std::vector< std::vector< vpMunkres::ZERO_T > > &, std::vector< bool > &, std::vector< bool > &)
Possible candidates:
  'template < Type >
  static STEP_T vpMunkres::stepTwo(std::vector< std::vector< Type > > &costs, std::vector< std::vector< ZERO_T > > &mask, std::vector< bool > &row_cover, std::vector< bool > &col_cover)'
  'template < Type >
  vpMunkres::STEP_T vpMunkres::stepTwo(std::vector< std::vector< Type > > &costs, std::vector< std::vector< vpMunkres::ZERO_T > > &mask, std::vector< bool > &row_cover, std::vector< bool > &col_cover)'

/Users/visp/visp_ws/visp/modules/core/src/munkres/vpMunkres.cpp:480: warning: no matching class member found for 
  template std::tuple< vpMunkres::STEP_T, std::optional< std::pair< unsigned int, unsigned int > > > vpMunkres::stepFour< input_data_type >(const std::vector< std::vector< double > > &, std::vector< std::vector< vpMunkres::ZERO_T > > &, std::vector< bool > &, std::vector< bool > &)
Possible candidates:
  'template < Type >
  static std::tuple< STEP_T, std::optional< std::pair< unsigned int, unsigned int > > > vpMunkres::stepFour(const std::vector< std::vector< Type > > &costs, std::vector< std::vector< ZERO_T > > &mask, std::vector< bool > &row_cover, std::vector< bool > &col_cover)'
  'template < Type >
  std::tuple< vpMunkres::STEP_T, std::optional< std::pair< unsigned int, unsigned int > > > vpMunkres::stepFour(const std::vector< std::vector< Type > > &costs, std::vector< std::vector< vpMunkres::ZERO_T > > &mask, std::vector< bool > &row_cover, std::vector< bool > &col_cover)'

/Users/visp/visp_ws/visp/modules/core/src/munkres/vpMunkres.cpp:310: warning: Unsupported xml/html tag <path_row_0> found
```

**Comment by JuInria** [comment]
> @JuInria It remains 2 doxygen warnings. Can you try to fix them
> 
> ```
> /Users/visp/visp_ws/visp/modules/core/src/munkres/vpMunkres.cpp:477: warning: no matching class member found for 
>   template vpMunkres::STEP_T vpMunkres::stepTwo< input_data_type >(std::vector< std::vector< double > > &, std::vector< std::vector< vpMunkres::ZERO_T > > &, std::vector< bool > &, std::vector< bool > &)
> Possible candidates:
>   'template < Type >
>   static STEP_T vpMunkres::stepTwo(std::vector< std::vector< Type > > &costs, std::vector< std::vector< ZERO_T > > &mask, std::vector< bool > &row_cover, std::vector< bool > &col_cover)'
>   'template < Type >
>   vpMunkres::STEP_T vpMunkres::stepTwo(std::vector< std::vector< Type > > &costs, std::vector< std::vector< vpMunkres::ZERO_T > > &mask, std::vector< bool > &row_cover, std::vector< bool > &col_cover)'
> 
> /Users/visp/visp_ws/visp/modules/core/src/munkres/vpMunkres.cpp:480: warning: no matching class member found for 
>   template std::tuple< vpMunkres::STEP_T, std::optional< std::pair< unsigned int, unsigned int > > > vpMunkres::stepFour< input_data_type >(const std::vector< std::vector< double > > &, std::vector< std::vector< vpMunkres::ZERO_T > > &, std::vector< bool > &, std::vector< bool > &)
> Possible candidates:
>   'template < Type >
>   static std::tuple< STEP_T, std::optional< std::pair< unsigned int, unsigned int > > > vpMunkres::stepFour(const std::vector< std::vector< Type > > &costs, std::vector< std::vector< ZERO_T > > &mask, std::vector< bool > &row_cover, std::vector< bool > &col_cover)'
>   'template < Type >
>   std::tuple< vpMunkres::STEP_T, std::optional< std::pair< unsigned int, unsigned int > > > vpMunkres::stepFour(const std::vector< std::vector< Type > > &costs, std::vector< std::vector< vpMunkres::ZERO_T > > &mask, std::vector< bool > &row_cover, std::vector< bool > &col_cover)'
> 
> /Users/visp/visp_ws/visp/modules/core/src/munkres/vpMunkres.cpp:310: warning: Unsupported xml/html tag <path_row_0> found
> ```

The doxygen warning is fixed but I do not get the `no matching class member found` messages. I'm using **cmake 3.16.3** and **ubuntu 20.04**. 

It seems to be a linking problem due to the template. Does it also occur with `stepOne` and `stepSix` ?

**Pull request merged**
