### PR TITLE
Add Simd intrinsics for Arm architecture into MBT code

### PR DESCRIPTION
**Pull request by s-trinh**
- current MBT code tries to use some SSE optimizations for better performance, this PR tries to use OpenCV HAL for universal intrinsics or Arm intrinsics if OpenCV is not available/version is too old
- try to update the Simd third-party lib to a recent version, SSE4 is the minimum requirement with this version

---

I would be interested to have the output of this perf test ("perfGenericTracker --benchmark") on Mac platform, since recent Mac computers use now Arm architecture (the same architecture than Raspberry PI or smartphone).

### CODE REVIEW

**Comment by fspindle** [comment]
Below are the benchmark results on my Macbook M1 pro (Neon):

```
% ./perfGenericTracker --benchmark
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfGenericTracker is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark generic tracker
-------------------------------------------------------------------------------
/Users/fspindle/soft/visp/visp_ws/test-pr/visp-s-trinh/visp/modules/tracker/mbt/test/generic-with-dataset/perfGenericTracker.cpp:117
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
Edge MBT                                       100             1     11.4662 s 
                                        113.065 ms    112.884 ms    113.309 ms 
                                        1.06516 ms    827.141 us    1.42539 ms 
                                                                               > 14 points

Edge + Depth dense MBT                         100             1     40.0877 s 
                                        259.902 ms    258.996 ms    261.075 ms 
                                         5.2477 ms    4.19629 ms    6.55161 ms 
                                                                               > 14 points

KLT MBT                                        100             1     13.1815 s 
                                        103.433 ms    100.914 ms    106.627 ms 
                                        14.3405 ms    11.8931 ms    18.3337 ms 
                                                                               > 14 points

KLT + depth dense MBT                          100             1     40.2013 s 
                                        371.631 ms    368.016 ms    376.146 ms 
                                        20.5846 ms    17.0711 ms    27.5633 ms 
                                                                               > 14 points

Edge + KLT + depth dense MBT                   100             1     44.2206 s 
                                        382.025 ms    378.684 ms    386.319 ms 
                                        19.2415 ms    15.4814 ms    25.0668 ms 
                                                                               

===============================================================================
All tests passed (13 assertions in 1 test case)
```

**Comment by fspindle** [comment]
On my macbook the following tests are failing in `testImageLoadSave.cpp`:
1. Test RGBA JPEG image loading
2. Test RGBA PNG image loading

Here the backtrace after a crash in the first test
```
Assertion failed: (0), function PixelSize, file SimdView.hpp, line 1117.
Process 57992 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x00000001013514a0 libvisp_core.3.5.dylib`Simd::Base::ImageJpegLoader::FromStream() [inlined] Simd::View<Simd::Allocator>::PixelSize(format=Bgra32 | Double) at SimdView.hpp:1117:18
   1114	        case Double:    return 8;
   1115	        case Rgb24:     return 3;
   1116	        case Rgba32:    return 4;
-> 1117	        default: assert(0); return 0;
   1118	        }
   1119	    }
   1120	
Target 0: (testImageLoadSave) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #0: 0x00000001a01d6d98 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x00000001a020bee0 libsystem_pthread.dylib`pthread_kill + 288
    frame #2: 0x00000001a0146340 libsystem_c.dylib`abort + 168
    frame #3: 0x00000001a0145754 libsystem_c.dylib`__assert_rtn + 272
  * frame #4: 0x00000001013514a0 libvisp_core.3.5.dylib`Simd::Base::ImageJpegLoader::FromStream() [inlined] Simd::View<Simd::Allocator>::PixelSize(format=Bgra32 | Double) at SimdView.hpp:1117:18
    frame #5: 0x00000001013513d0 libvisp_core.3.5.dylib`Simd::Base::ImageJpegLoader::FromStream() [inlined] Simd::View<Simd::Allocator>::Recreate(this=0x0000600002c054c8, w=640, h=440, f=Bgra32 | Double, d=0x0000000000000000, align=16) at SimdView.hpp:977:55
    frame #6: 0x000000010135123c libvisp_core.3.5.dylib`Simd::Base::ImageJpegLoader::FromStream(this=0x0000600002c05480) at SimdBaseImageLoadJpeg.cpp:2429:24
    frame #7: 0x000000010142730c libvisp_core.3.5.dylib`Simd::Neon::ImageLoadFromMemory(data="\xff\xd8\xff\xdb", size=94983, stride=0x000000016fdfe388, width=0x000000016fdfe380, height=0x000000016fdfe378, format=0x000000016fdfe374) at SimdNeonImageLoad.cpp:146:33
    frame #8: 0x000000010134b8a0 libvisp_core.3.5.dylib`Simd::ImageLoadFromFile(loader=(libvisp_core.3.5.dylib`Simd::Neon::ImageLoadFromMemory(unsigned char const*, unsigned long, unsigned long*, unsigned long*, unsigned long*, SimdPixelFormatType*) at SimdNeonImageLoad.cpp:139), path="/Users/fspindle/soft/visp/visp-images/Solvay/Solvay_conference_1927_Version2_640x440.jpg", stride=0x000000016fdfe388, width=0x000000016fdfe380, height=0x000000016fdfe378, format=0x000000016fdfe374)(unsigned char const*, unsigned long, unsigned long*, unsigned long*, unsigned long*, SimdPixelFormatType*), char const*, unsigned long*, unsigned long*, unsigned long*, SimdPixelFormatType*) at SimdBaseImageLoad.cpp:48:24
    frame #9: 0x0000000101331e6c libvisp_core.3.5.dylib`::SimdImageLoadFromFile(path="/Users/fspindle/soft/visp/visp-images/Solvay/Solvay_conference_1927_Version2_640x440.jpg", stride=0x000000016fdfe388, width=0x000000016fdfe380, height=0x000000016fdfe378, format=0x000000016fdfe374) at SimdLib.cpp:515:12
    frame #10: 0x00000001006aa760 libvisp_io.3.5.dylib`readSimdlib(I=0x000000016fdfe930, filename="/Users/fspindle/soft/visp/visp-images/Solvay/Solvay_conference_1927_Version2_640x440.jpg") at vpImageIoSimd.cpp:61:19
    frame #11: 0x00000001006cb2cc libvisp_io.3.5.dylib`vpImageIo::readJPEG(I=0x000000016fdfe930, filename="/Users/fspindle/soft/visp/visp-images/Solvay/Solvay_conference_1927_Version2_640x440.jpg", backend=3) at vpImageIo.cpp:484:5
    frame #12: 0x00000001006cb0f8 libvisp_io.3.5.dylib`vpImageIo::read(I=0x000000016fdfe930, filename="/Users/fspindle/soft/visp/visp-images/Solvay/Solvay_conference_1927_Version2_640x440.jpg", backend=3) at vpImageIo.cpp:244:5
    frame #13: 0x00000001000de588 testImageLoadSave`____C_A_T_C_H____T_E_S_T____3() at testImageLoadSave.cpp:157:7
    frame #14: 0x000000010000a644 testImageLoadSave`Catch::TestInvokerAsFunction::invoke(this=0x0000600000004040) const at catch.hpp:14321:9
    frame #15: 0x000000010008bf8c testImageLoadSave`Catch::TestCase::invoke(this=0x00000001078098a0) const at catch.hpp:14160:15
    frame #16: 0x000000010008beac testImageLoadSave`Catch::RunContext::invokeActiveTestCase(this=0x000000016fdff140) at catch.hpp:13020:27
    frame #17: 0x0000000100086930 testImageLoadSave`Catch::RunContext::runCurrentTest(this=0x000000016fdff140, redirectedCout="", redirectedCerr="") at catch.hpp:12993:17
    frame #18: 0x0000000100085f4c testImageLoadSave`Catch::RunContext::runTest(this=0x000000016fdff140, testCase=0x00000001078098a0) at catch.hpp:12754:13
    frame #19: 0x0000000100094c6c testImageLoadSave`Catch::(anonymous namespace)::TestGroup::execute(this=0x000000016fdff130) at catch.hpp:13347:45
    frame #20: 0x0000000100092fc8 testImageLoadSave`Catch::Session::runInternal(this=0x000000016fdff3d0) at catch.hpp:13553:39
    frame #21: 0x0000000100092e04 testImageLoadSave`Catch::Session::run(this=0x000000016fdff3d0) at catch.hpp:13509:24
    frame #22: 0x00000001000e24dc testImageLoadSave`main(argc=1, argv=0x000000016fdff6d0) at testImageLoadSave.cpp:318:27
    frame #23: 0x000000010045908c dyld`start + 520
```

And here the backtrace when the crash occurs in the second test
```
Assertion failed: (0), function PixelSize, file SimdView.hpp, line 1117.
Process 58853 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x00000001013514a0 libvisp_core.3.5.dylib`Simd::Base::ImageJpegLoader::FromStream() [inlined] Simd::View<Simd::Allocator>::PixelSize(format=Bgra32 | Double) at SimdView.hpp:1117:18
   1114	        case Double:    return 8;
   1115	        case Rgb24:     return 3;
   1116	        case Rgba32:    return 4;
-> 1117	        default: assert(0); return 0;
   1118	        }
   1119	    }
   1120	
Target 0: (testImageLoadSave) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #0: 0x00000001a01d6d98 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x00000001a020bee0 libsystem_pthread.dylib`pthread_kill + 288
    frame #2: 0x00000001a0146340 libsystem_c.dylib`abort + 168
    frame #3: 0x00000001a0145754 libsystem_c.dylib`__assert_rtn + 272
  * frame #4: 0x00000001013514a0 libvisp_core.3.5.dylib`Simd::Base::ImageJpegLoader::FromStream() [inlined] Simd::View<Simd::Allocator>::PixelSize(format=Bgra32 | Double) at SimdView.hpp:1117:18
    frame #5: 0x00000001013513d0 libvisp_core.3.5.dylib`Simd::Base::ImageJpegLoader::FromStream() [inlined] Simd::View<Simd::Allocator>::Recreate(this=0x0000600002c01c48, w=640, h=440, f=Bgra32 | Double, d=0x0000000000000000, align=16) at SimdView.hpp:977:55
    frame #6: 0x000000010135123c libvisp_core.3.5.dylib`Simd::Base::ImageJpegLoader::FromStream(this=0x0000600002c01c00) at SimdBaseImageLoadJpeg.cpp:2429:24
    frame #7: 0x000000010142730c libvisp_core.3.5.dylib`Simd::Neon::ImageLoadFromMemory(data="\xff\xd8\xff\xdb", size=94983, stride=0x000000016fdfe388, width=0x000000016fdfe380, height=0x000000016fdfe378, format=0x000000016fdfe374) at SimdNeonImageLoad.cpp:146:33
    frame #8: 0x000000010134b8a0 libvisp_core.3.5.dylib`Simd::ImageLoadFromFile(loader=(libvisp_core.3.5.dylib`Simd::Neon::ImageLoadFromMemory(unsigned char const*, unsigned long, unsigned long*, unsigned long*, unsigned long*, SimdPixelFormatType*) at SimdNeonImageLoad.cpp:139), path="/Users/fspindle/soft/visp/visp-images/Solvay/Solvay_conference_1927_Version2_640x440.jpg", stride=0x000000016fdfe388, width=0x000000016fdfe380, height=0x000000016fdfe378, format=0x000000016fdfe374)(unsigned char const*, unsigned long, unsigned long*, unsigned long*, unsigned long*, SimdPixelFormatType*), char const*, unsigned long*, unsigned long*, unsigned long*, SimdPixelFormatType*) at SimdBaseImageLoad.cpp:48:24
    frame #9: 0x0000000101331e6c libvisp_core.3.5.dylib`::SimdImageLoadFromFile(path="/Users/fspindle/soft/visp/visp-images/Solvay/Solvay_conference_1927_Version2_640x440.jpg", stride=0x000000016fdfe388, width=0x000000016fdfe380, height=0x000000016fdfe378, format=0x000000016fdfe374) at SimdLib.cpp:515:12
    frame #10: 0x00000001006aa760 libvisp_io.3.5.dylib`readSimdlib(I=0x000000016fdfe930, filename="/Users/fspindle/soft/visp/visp-images/Solvay/Solvay_conference_1927_Version2_640x440.jpg") at vpImageIoSimd.cpp:61:19
    frame #11: 0x00000001006cb2cc libvisp_io.3.5.dylib`vpImageIo::readJPEG(I=0x000000016fdfe930, filename="/Users/fspindle/soft/visp/visp-images/Solvay/Solvay_conference_1927_Version2_640x440.jpg", backend=3) at vpImageIo.cpp:484:5
    frame #12: 0x00000001006cb0f8 libvisp_io.3.5.dylib`vpImageIo::read(I=0x000000016fdfe930, filename="/Users/fspindle/soft/visp/visp-images/Solvay/Solvay_conference_1927_Version2_640x440.jpg", backend=3) at vpImageIo.cpp:244:5
    frame #13: 0x00000001000df184 testImageLoadSave`____C_A_T_C_H____T_E_S_T____3() at testImageLoadSave.cpp:157:7
    frame #14: 0x000000010000b240 testImageLoadSave`Catch::TestInvokerAsFunction::invoke(this=0x0000600000008200) const at catch.hpp:14321:9
    frame #15: 0x000000010008cb88 testImageLoadSave`Catch::TestCase::invoke(this=0x0000000107705cb0) const at catch.hpp:14160:15
    frame #16: 0x000000010008caa8 testImageLoadSave`Catch::RunContext::invokeActiveTestCase(this=0x000000016fdff140) at catch.hpp:13020:27
    frame #17: 0x000000010008752c testImageLoadSave`Catch::RunContext::runCurrentTest(this=0x000000016fdff140, redirectedCout="", redirectedCerr="") at catch.hpp:12993:17
    frame #18: 0x0000000100086b48 testImageLoadSave`Catch::RunContext::runTest(this=0x000000016fdff140, testCase=0x0000000107705cb0) at catch.hpp:12754:13
    frame #19: 0x0000000100095868 testImageLoadSave`Catch::(anonymous namespace)::TestGroup::execute(this=0x000000016fdff130) at catch.hpp:13347:45
    frame #20: 0x0000000100093bc4 testImageLoadSave`Catch::Session::runInternal(this=0x000000016fdff3d0) at catch.hpp:13553:39
    frame #21: 0x0000000100093a00 testImageLoadSave`Catch::Session::run(this=0x000000016fdff3d0) at catch.hpp:13509:24
    frame #22: 0x00000001000e26dc testImageLoadSave`main(argc=1, argv=0x000000016fdff6d0) at testImageLoadSave.cpp:318:27
    frame #23: 0x000000010045908c dyld`start + 520
```

**Comment by s-trinh** [comment]
@fspindle Thanks for the debug trace.
The last commit should fix it.

---

About the PR, some following code are probably missing:

https://github.com/lagadic/visp/blob/263d5b26db6908edb38f6792aff9be77382f3a81/3rdparty/simdlib/Simd/SimdSse41GaussianBlur.cpp#L346-L348

Is there a way to know which files need this `else` branch?

---

Could you also copy/paste the output of `./perfGenericTracker --benchmark` with ViSP built from master on your M1 pro?
Thanks.

**Comment by fspindle** [comment]
Since `libvisp_simdlib` is built as a static library, the code you mention below was introduced to mute a compiler warning (`libvisp_simdlib.a(file) has no symbol` when SSE41 is not available. 

https://github.com/lagadic/visp/blob/263d5b26db6908edb38f6792aff9be77382f3a81/3rdparty/simdlib/Simd/SimdSse41GaussianBlur.cpp#L346-L348

The `else` branch is never used.

We have the same kind of things in all the `SimdAvx2*.cpp` files.

Looking at `SimdSse41*.cpp` files, I'm quite surprised that this workaround is only in `SimdSse41GaussianBlur.cpp` and `SimdSse41Resizer.cpp`.
Same for `SimdNeon*.cpp` files where it is only in `SimdNeonCustomFunctions.cpp`.

I will check that on my side on macOS and let you know.

**Comment by fspindle** [comment]
I confirm that your last commit fixes `testImageLoadSave.cpp`.

Below are benchmark results on my Macbook M1 pro using `master` branch:
```
% ./perfGenericTracker --benchmark
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
perfGenericTracker is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
Benchmark generic tracker
-------------------------------------------------------------------------------
/Users/fspindle/soft/visp/visp_ws/visp/modules/tracker/mbt/test/generic-with-dataset/perfGenericTracker.cpp:117
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
Edge MBT                                       100             1     11.8891 s 
                                        116.771 ms     116.49 ms    117.077 ms 
                                        1.48651 ms     1.2717 ms    1.79366 ms 

Edge + Depth dense MBT                         100             1     46.8013 s 
                                        426.399 ms    425.551 ms    427.217 ms 
                                        4.27963 ms    3.92749 ms    4.67799 ms 

KLT MBT                                        100             1     11.0742 s 
                                        89.3894 ms    88.8357 ms    90.0953 ms 
                                        3.17127 ms    2.61402 ms    4.15571 ms 

KLT + depth dense MBT                          100             1     53.3197 s 
                                        488.468 ms    487.058 ms    490.584 ms 
                                        8.69865 ms    6.50643 ms    13.6401 ms 

Edge + KLT + depth dense MBT                   100             1     52.0091 s 
                                        490.314 ms     488.53 ms    492.593 ms 
                                        10.2209 ms    8.32088 ms    12.7445 ms 
                                                                               

===============================================================================
All tests passed (13 assertions in 1 test case)
```

It shows a significant acceleration when depth dense feature is used.

**Comment by fspindle** [comment]
@s-trinh Ready to merge on my side.

**Comment by s-trinh** [comment]
@fspindle 
Ok for me also.

**Comment by fspindle** [comment]
See also #1110 where `#define _FILE_OFFSET_BITS 64` is used to fix `testVideo.cpp` on `other-arch-isolated.yml` workflow on Ubuntu 22.04 armv7

**Pull request merged**
